Task was destroyed but is pending!
webfucktory/python-events-manager pull request #6
Opened 2023-05-17 08:50 UTC by al-little

Added a set to keep a reference to the tasks while in progress so that they are not garbage collected.

2023-05-17 12:58 UTC, y-martini commented
@al-little what about tests?

2023-05-17 14:33 UTC, al-little commented
Hi Yuriy,

The bug occurs when longer running tasks get garbage collected before
completing.
I am using asyncio and the Bleak Bluetooth library and was getting the
exception occasionally. I am relatively new to Python development and found
it difficult to create a failing test.

Thanks,

Al

On Wed, 17 May 2023 at 13:59, Yuriy Martini ***@***.***>
wrote:

> @al-little <https://github.com/al-little> what about tests?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/webfucktory/python-events-manager/pull/6#issuecomment-1551346607>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AALP75QB7RJATNH2WIU7YGTXGTDRPANCNFSM6AAAAAAYEYJMX4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-17 17:36 UTC, albertogferrario commented
Hello @al-little, thanks for being a `fucktory` contributor. 
I reviewed the contribution and left some comments. I will be happy to answer any questions.

2023-05-25 09:35 UTC, albertogferrario requested changes
The following changes have to be provided before merge:
- [ ] remove blank lines at 75 and 77;
- [ ] restore logging and blank line at line 74 and 75

2023-05-25 09:35 UTC, albertogferrario commented on events_manager/__init__.py
> +async def __run_listeners(e: Event) -> None:
Could you please explain why you consider to alter its visibility?

2023-05-25 09:58 UTC, al-little commented on events_manager/__init__.py
> +async def __run_listeners(e: Event) -> None:
I accidentally added dunder '__'. The original code used single '_'.

2023-06-13 08:21 UTC, al-little commented
Morning. Any chance of progressing the pull request? Please let me know if there is anything else I need to do.

2023-06-15 05:58 UTC, albertogferrario approved these changes
Thank you for your contribution!

2023-06-15 08:27 UTC, albertogferrario commented
Hello @al-little, sorry for bothering you but checks fail because of lint issues, you can find more details [here](https://github.com/webfucktory/python-events-manager/actions/runs/5264436242/jobs/9540667164).
I suggest you to run the `lint` script locally, you can find it in repository root.
If you have any doubts do not hesitate to contact me.
Thank you.

2023-06-15 09:09 UTC, merged